# Generated by Django 5.0 on 2024-01-09 04:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_company_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание зала')),
                ('count_places', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('number_of_rows', models.PositiveSmallIntegerField(verbose_name='Количество рядов')),
                ('number_of_places', models.PositiveSmallIntegerField(verbose_name='Количество мест в ряду')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Seanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сеанса')),
                ('time', models.TimeField(verbose_name='Время сеанса')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seanses', to='movies.movie', verbose_name='Фильм')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seanses', to='movies.saloon', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ('date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='SectorSaloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сектора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сектора')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='movies.saloon', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Сектор зала',
                'verbose_name_plural': 'Секторы залов',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveSmallIntegerField(verbose_name='Номер ряда')),
                ('row_place', models.PositiveSmallIntegerField(verbose_name='Номер места')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='movies.sectorsaloon', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default=uuid.uuid4, editable=False, max_length=40, verbose_name='Номер билета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания билета')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления билета')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('booked', models.BooleanField(default=False, verbose_name='Забронирован')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='movies.place', verbose_name='Место')),
                ('seanse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='movies.seanse', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ('seanse', 'place'),
            },
        ),
    ]
